export const caseStudies = [
  {
    id: "perth-fashion-nails",
    name: "Fashion Nails Morley",
    city: "Perth, WA",
    category: "Nail & Beauty Studio",
    beforeValue: "8",
    afterValue: "38",
    unit: "lịch hẹn/tuần",
    unitEn: "bookings/wk",
    growth: "+375%",
    highlight: "Tỷ lệ quay lại 42%",
    highlightEn: "42% Return Rate",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
    tags: ["Google Maps Local SEO", "Online Booking System", "Perth WA"],
  },
  {
    id: "melbourne-luxe-nails",
    name: "Luxe Nail Lounge",
    city: "Chadstone, Melbourne",
    category: "Luxe Nail & Lash Bar",
    beforeValue: "12",
    afterValue: "48",
    unit: "khách VIP/tháng",
    unitEn: "VIP clients/mo",
    growth: "+300%",
    highlight: "Tăng 65% doanh thu khách cũ",
    highlightEn: "+65% Repeat Revenue",
    image: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80",
    tags: ["Automated CRM Flow", "VIP Loyalty Program", "Melbourne VIC"],
  },
  {
    id: "brisbane-sunnybank",
    name: "Sunnybank Nail & Spa",
    city: "Sunnybank, Brisbane",
    category: "Nail Art & Eyelash Studio",
    beforeValue: "$14",
    afterValue: "$3.2",
    unit: "chi phí/khách mới",
    unitEn: "cost per lead",
    growth: "-77%",
    highlight: "120+ khách mới/tháng",
    highlightEn: "120+ New Bookings/Mo",
    image: "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=800&q=80",
    tags: ["Meta Hyperlocal Ads", "Full Booking Pipeline", "Brisbane QLD"],
  },
];
