export const caseStudies = [
  {
    id: "perth-a",
    city: "Perth, WA",
    category: "Nail & Beauty Salon",
    beforeValue: 5,
    afterValue: 25,
    unit: "yêu cầu/tuần",
    unitEn: "enquiries/wk",
    growth: "+400%",
    highlight: "Tỷ lệ quay lại 32%",
    highlightEn: "32% Repeat Rate",
    image: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "melbourne-b",
    city: "Melbourne, VIC",
    category: "Luxe Nail Studio",
    beforeValue: 8,
    afterValue: 32,
    unit: "khách/tháng",
    unitEn: "leads/mo",
    growth: "+300%",
    highlight: "Top 1 Tìm Kiếm Local",
    highlightEn: "Top 1 Local Search",
    image: "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "brisbane-c",
    city: "Brisbane, QLD",
    category: "Wellness & Nail Spa",
    beforeValue: 12,
    afterValue: 41,
    unit: "lịch hẹn/tuần",
    unitEn: "bookings/wk",
    growth: "+241%",
    highlight: "Tự động hóa 100%",
    highlightEn: "100% Automated Flow",
    image: "https://images.unsplash.com/photo-1560750588-73207b1ef5b8?auto=format&fit=crop&w=1200&q=85",
  },
  {
    id: "sydney-d",
    city: "Sydney, NSW",
    category: "Premium Beauty Clinic",
    beforeValue: 6,
    afterValue: 29,
    unit: "khách VIP/tháng",
    unitEn: "clients/mo",
    growth: "+383%",
    highlight: "X3 Doanh Thu",
    highlightEn: "3X Monthly Revenue",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1200&q=85",
  },
];
